name: Test

on:
  push:
    paths-ignore: 
      - README.md
  pull_request:
    paths-ignore: 
      - README.md

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

        nim-version:
          - '2.0.0'
          - stable
          - devel

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v4
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version}}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('*.nimble') }}
        # restore-keys: |
        #   ${{ runner.os }}-nimble-${{ matrix.nim-version}}-
      # if: runner.os != 'Windows'
    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}

    - name: Install Packages
      run: nimble install -y

    - name: Test
      run: nimble -y --silent test